# Generated by Django 5.0.3 on 2024-03-13 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Businesss',
            fields=[
                ('first_name', models.TextField(blank=True, null=True)),
                ('last_name', models.TextField(blank=True, null=True)),
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('firstname', models.TextField(blank=True, db_comment='changes', null=True)),
            ],
            options={
                'db_table': 'business_name',
                'managed': True,
            },
        ),
    ]
